from .db.base_class import Base
from .backlist_token import BlacklistToken
from .user import *
from .storage import *
from .academic_year import * 
from .semester import *
from .programs import *
from .speciality import *
from .group import *
from .students import *
from .subjects import *
from .exams_type import *
from .professors import *
from .courses import *
from .teacher_course_assignments import *
from .student_exam_notes import *
from .types_courses import *