from .params import CustomParams
from .admin_key import AdminKey
from .msg import Msg, BoolStatus, DataDisplay
from .base import DataList
from .user import *
from .file import *
from .academic_year import *
from .semester import *
from .programs import *
from .speciality import *
from .group import *
from .students import *
from .subjects import *
from .examns_type import *
from .teacher import *
from .courses import *
from .teacher_course_assignment import *
from .student_exam_notes import *
from .types_courses import *